version: '3.8'
services:
  influxdb:
    build:
      context: .
      dockerfile: Dockerfile.influxdb
    ports:
      - "8086:8086"
    networks:
      - k6

  grafana:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.grafana
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - k6
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      # - DS_K6=myinfluxdb
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
    - type: bind
      source: "./datasources/default.yaml"
      target: /etc/grafana/provisioning/datasources/default.yaml
    - type: bind
      source: "./dashboards/default.yaml"
      target: /etc/grafana/provisioning/dashboards/default.yaml
    - type: bind
      source: "./dashboard.json"
      target: /var/lib/grafana/dashboards/dashboard.json           

  k6:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.k6
    image: loadimpact/k6:latest
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    command: 'version'
    networks:
      - k6

networks:
  k6: